name: EvalCrafter
channels:
  - defaults
dependencies:
  - pip=23.2.1
  - python=3.9.17

  - pip:
      - accelerate==0.22.0
      - beautifulsoup4==4.12.2
      - cython==3.0.2
      - diffusers==0.20.1
      - einops==0.6.1
      - ffmpy==0.3.1
      - huggingface-hub==0.17.3
      - imageio==2.31.1
      - ipdb==0.13.13
      - ipykernel==6.25.1
      - ipython==8.14.0
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.0
      - jinja2==3.1.2
      - json-tricks==3.17.3
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.19.0
      - jsonschema-specifications==2023.7.1
      - jupyter==1.0.0
      - lmdb==1.4.1
      - lxml==4.9.3
      - markdown==3.4.4
      - markdown-it-py==2.2.0
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.6
      - mmcv==2.0.1
      - mmdet==3.1.0
      - mmengine==0.8.4
      - mmpose==1.1.0
      - model-index==0.1.11
      - networkx==3.1
      - ninja==1.11.1
      - nltk==3.8.1
      - notebook==7.0.2
      - notebook-shim==0.2.3
      - numpy==1.22.0
      - onnx==1.14.1
      - open-clip-torch==2.20.0
      - openai-clip==1.0.1
      - opencv-contrib-python==4.6.0.66
      - opencv-python==4.6.0.66
      - packaging==23.1
      - paddle-bfloat==0.1.7
      - paddleocr==2.7.0.3
      - paddlepaddle-gpu==2.5.1
      - pandas==1.3.5
      - pillow==10.0.1
      - pycocoevalcap==1.2
      - pycocotools==2.0.7
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - safetensors==0.3.3
      - scikit-image==0.21.0
      - scikit-video==1.1.11
      - scipy==1.11.2
      - sentencepiece==0.1.99
      - setuptools==60.2.0
      - timm==0.4.12
      - tokenizers==0.13.3
      - torch==2.0.1
      - torchmetrics==1.2.0
      - torchvision==0.15.2
      - tornado==6.3.3
      - tqdm==4.66.1
      - transformers==4.33.2
      - triton==2.0.0
      - wandb==0.15.8
      - tensorflow==2.12.0
      - deprecated
      - gdown
      - decord
      - pybind11
      - fastwer
      - cer
      - mmaction2==1.1.0       
      - supervision==0.6.0  
